### ISSUE TITLE
GENERATE BUTTON DOESNT WORK

### ISSUE THREAD

**Issue by demirklvc** [AUTOMATIC1111/stable-diffusion-webui-promptgen#2]
.

**Comment by Nacurutu** [comment]
FIXED.

**Comment by Nebuluss** [comment]
still not working for me

**Comment by dobrado76** [comment]
You probably need to update your Stable Diffusion. It was not working before I update to the current version. It is now working at least with the current version of Stable Diffusion Automatic 1111.

**Comment by DarkAlchy** [comment]
Not working here and I updated a few hours ago.

This may have something to do with it:

ValueError: File cannot be fetched: D:/stable-diffusion-webui/extensions/stable-diffusion-webui-promptgen/javascript/promptgen.js. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.

**Comment by robbiep** [comment]
Pressing Generate throws this console error
```
2087 Uncaught (in promise) ReferenceError: randomId is not defined
    at submit_promptgen (?__theme=dark:2087:14)
    at eval (eval at <anonymous> (index.0b923826.js:75:2081), <anonymous>:3:38)
    at index.0b923826.js:34:32309
    at HTMLButtonElement.<anonymous> (index.0b923826.js:76:2455)
    at index.0b923826.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.ae (index.0b923826.js:4:1253)
    at HTMLButtonElement._ (Button.svelte:10:48)
    at index.0b923826.js:4:1266
    at Array.forEach (<anonymous>)
```

**Comment by robbiep** [comment]
Error here - https://github.com/AUTOMATIC1111/stable-diffusion-webui-promptgen/blob/master/javascript/promptgen.js#L16

**Comment by robbiep** [comment]
Solution to this problem...

Update
```
    var id = randomId()
```
to
```
var id = Math.trunc(Math.random() * 100000000)
```

**Comment by dkhold** [comment]
Yup, it's borked:

```
Uncaught (in promise) ReferenceError: submit_promptgen is not defined
    at Object.eval [as frontend_fn] (eval at <anonymous> (Blocks.svelte:67:25), <anonymous>:3:14)
    at je (Blocks.svelte:277:6)
eval @ VM1797:3
je @ Blocks.svelte:277
Promise.then (async)
je @ Blocks.svelte:282
await in je (async)
(anonymous) @ Blocks.svelte:373
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
f @ Button.svelte:12
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
v @ Button.svelte:11
```
