### ISSUE TITLE
Top K Integer Error

### ISSUE THREAD

**Issue by Pyurah** [AUTOMATIC1111/stable-diffusion-webui-promptgen#3]
It looks like you can only use Integers when setting the "Top K" value. However, sliding bar adjusts with decimal.

Exception encountered while attempting to generate prompt: "top_k" has to be a strictly positive integer, but is 9.2

**Comment by Pyurah** [comment]
Here is the full exception.

Exception encountered while attempting to generate prompt: `top_k` has to be a strictly positive integer, but is 9.2
Traceback (most recent call last):
  File "E:\sdwebui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sdwebui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\sdwebui\venv\lib\site-packages\gradio\blocks.py", line 935, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
