### ISSUE TITLE
Error: Exception in ASGI application

### ISSUE THREAD

**Issue by Woisek** [AUTOMATIC1111/stable-diffusion-webui-promptgen#9]
When I use promptgen to henerate some prompt using it the first time, sometimes I get the following error:

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=89508.671 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Programme\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 362, in timeout_keep_alive_handler
    self.conn.send(event)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 493, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 242, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 251, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_BODY
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 105, in __call__
    await response(scope, receive, send)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 266, in __call__
    async with anyio.create_task_group() as task_group:
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 269, in wrap
    await func()
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 263, in stream_response
    await send({"type": "http.response.body", "body": b"", "more_body": False})
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
    await send(message)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 512, in send
    output = self.conn.send(event)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 483, in send_with_data_passthrough
    raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR

Any ideas?

**Comment by super3** [comment]
@Woisek Getting the same error. Did you ever fix this?

**Comment by sledgehkg** [comment]
I just started getting this error today, been looking but can't find a solution.
